### ISSUE TITLE
single root node

### ISSUE THREAD

**Issue by matthiaskoch** [wobsoriano/vue-lite-youtube-embed#11]
Hello! 
I try to place it inside a vue app with router and get this error:

Multiple root nodes returned from render function. Render function should return a single root node.

found in

---> <LiteYouTubeEmbed>
       <HomeView> at src/views/HomeView.vue
         <App> at src/App.vue
           <Root>

Does it not work inside ChildViews ?

**Comment by wobsoriano** [comment]
Are you using Vue 2? If yes, update to `1.2.0` and follow the updated instructions in README. Thanks! Feel free to reopen.
