### ISSUE TITLE
aspectWidth and aspectHeight not working

### ISSUE THREAD

**Issue by just-another-peter** [wobsoriano/vue-lite-youtube-embed#14]
Setting aspectWidth and aspectHeight has no effect. 

I found `.yt-lite` has declared css variable for the new ratio, but `.yt-lite:after` is not using the css variable, hardcoded `padding-bottom: 56.25%;` in css file.

**Comment by wobsoriano** [comment]
Fixed https://github.com/wobsoriano/vue-lite-youtube-embed/commit/9cc2141da86725614e919e67d5430fcba4de987f
