### ISSUE TITLE
aria-label written wrong

### ISSUE THREAD

**Issue by ghost** [wobsoriano/vue-lite-youtube-embed#15]
Lighthouse reports that the play button has no valid name for screenreaders:
![image](https://github.com/wobsoriano/vue-lite-youtube-embed/assets/93664840/2f190ece-48a1-420f-a302-f5a5fbdaa291)

I think its because the button has the aria-label="" is written as arialabel="".

Could you please fix this? Thanks!

**Comment by wobsoriano** [comment]
Thanks, fixed!
