### ISSUE TITLE
Vue 2 haven't Fragment

### ISSUE THREAD

**Issue by vuthanhbayit** [wobsoriano/vue-lite-youtube-embed#16]
When I use this lib with Nuxt 2, I get 1 error
![image](https://github.com/wobsoriano/vue-lite-youtube-embed/assets/37856246/53fa287d-5ca0-414f-b62b-b565dcc20b82)
and I check in code, I see:
```tsx
if (isVue2)
      return () => h('Fragment', {}, vnodeList())
```
Tks for check

**Comment by wobsoriano** [comment]
It's written in README that if you use Vue 2, you'll have to install `vue-frag`.

```ts
import Vue from 'vue'
import { Fragment } from 'vue-frag'
import App from './App.vue'

Vue.component('Fragment', Fragment)

new Vue({
  render: h => h(App),
}).$mount('#app')
```
