### ISSUE TITLE
Play event not working, also not in the demo

### ISSUE THREAD

**Issue by fgd007** [wobsoriano/vue-lite-youtube-embed#17]
When you haven't interacted with the video yet, the play event gives an error: `iframe element not instantiated.`
The events work when you manually click the play button within the iframe.

**Comment by wobsoriano** [comment]
Unfortunately, you will have to play the video first before any of the methods work.

**Comment by fgd007** [comment]
Yes, I do understand it now. It is actually the whole point of this plugin I am realizing...
Would there be a way to trigger initializing of the iframe without clicking the button?

**Comment by fgd007** [comment]
The method provided [here](https://github.com/wobsoriano/vue-lite-youtube-embed/issues/6#issuecomment-1419355393)  in #6 seems to work.
