### ISSUE TITLE
Any plans to add some methods and events like in vue-youtube-embed?

### ISSUE THREAD

**Issue by Dylan190774** [wobsoriano/vue-lite-youtube-embed#3]
I always used [vue-youtube-embed](https://github.com/kaorun343/vue-youtube-embed)  which worked very well, but sadly doesn't work with Vue3.

This component has methods like `playVideo `and `pauseVideo` and also events like @ready, @playing, @ended and @paused.

Do you have plans to add these kind of features?

**Comment by wobsoriano** [comment]
I'll look into those events. This component is a straight-up port of https://github.com/ibrahimcesar/react-lite-youtube-embed

**Comment by NickyZeemanNL** [comment]
Any updates on this?

**Comment by wobsoriano** [comment]
Added https://github.com/wobsoriano/vue-lite-youtube-embed#methods

**Comment by kendrick-fnw** [comment]
Hi @wobsoriano thank you, but I can't get the event fired : @iframe-added="onReady" onReady isn't called. Any ideas please?
