### ISSUE TITLE
methods / events

### ISSUE THREAD

**Issue by Dylan190774** [wobsoriano/vue-lite-youtube-embed#4]
I always used [vue-youtube-embed](https://github.com/kaorun343/vue-youtube-embed)  which worked very well, but sadly doesn't work with Vue3.

This component has methods like `playVideo `and `pauseVideo` and also events like @ready, @playing, @ended and @paused.

Do you have plans to add these kind of features?

**Comment by fgd007** [comment]
@wobsoriano it would be awesome if this component could emit the playing, ended and paused events. Is this on your roadmap or would you consider out of the 'Lite' scope?
